# Playbook for fully provisioning all machines

# Base provisioning for all machines
- hosts: all
  roles:
    - base

# Internal network
- hosts: all
  any_errors_fatal: true  # mesh config will fail if any hosts are not available
  roles:
    - intnet
  tags:
    - intnet

# General tasks for all machines
- hosts: all
  roles:
    - common

# Setup Netdata for all machines
- hosts: all
  roles:
    - netdata
  tags:
    - netdata
