# Playbook for fully provisioning all machines

# Base provisioning for all machines
- hosts: all
  name: Base machine provisioning
  roles:
    - base
  tags:
    - base

# Host-specific root key generation
- hosts: all
  name: Host-specific root key generation
  roles:
    - hostkey
  tags:
    - hostkey

# Internal network
- hosts: all
  name: Internal network
  any_errors_fatal: true  # mesh config will fail if any hosts are not available
  roles:
    - intnet
  tags:
    - intnet

# General tasks for all machines
- hosts: all
  name: Common system tasks
  roles:
    - common
  tags:
    - common

# Setup Nginx on flagship
- hosts: flagship
  name: Install nginx
  roles:
    - nginx
  tags:
    - nginx

# Setup Netdata for all machines
- hosts: all
  name: Install netdata
  roles:
    - netdata
  tags:
    - netdata

# Setup CTFd on flagship
- hosts: flagship
  name: Install CTFd
  roles:
    - ctfd
  tags:
    - ctfd
