# Derive and store private key as fact
- name: Derive private key
  no_log: true  # avoid logging private keys
  ansible.builtin.set_fact:
    intnet_privkey:
      "{{ host_root_key | derive_key('wireguard-internal-network-key-1', 'base64', 32) }}"


# Derive public key from the private key (derivation is deterministic)
- name: Derive public key
  no_log: true  # avoid logging private keys (stdin)
  ansible.builtin.command:
    cmd: "wg pubkey"
    stdin: "{{ intnet_privkey }}"
  changed_when: false  # prevent this task from always changing
  register: intnet_pubkey

# Store public key as fact (to allow for cross-host references)
- name: Set public key fact
  ansible.builtin.set_fact:
    intnet_pubkey: "{{ intnet_pubkey.stdout | trim }}"
