- name: Install extra packages
  become: true
  ansible.builtin.dnf:
    state: present
    name: [
      git,
      nano,  # simple text editor
      micro,  # enhanced nano
      ripgrep,  # enhanced grep
    ]
