# Configure management user (before anything else)
- import_tasks: management_user.yaml

# Generic system configuration (hostnames, etc.)
- import_tasks: system_config.yaml

# Update system packages, etc.
- import_tasks: update_system.yaml
  tags:
  - update

# Install general packages for all machines
- import_tasks: general_packages.yaml

# General system hardening
- import_tasks: system_hardening.yaml

# Install netdata
- import_tasks: install_netdata.yaml
  tags:
  - netdata
