# Update system packages, etc.
- import_tasks: update_system.yaml
  tags:
    - update

# Install general packages for all machines
- import_tasks: general_packages.yaml

# Install netdata
- import_tasks: install_netdata.yaml
  tags:
    - netdata
