- name: Update system with dnf
  become: true
  block:

  - name: Upgrade all packages
    ansible.builtin.dnf:
      state: latest
      name: "*"

  - name: Cleanup unneeded packages
    ansible.builtin.dnf:
      autoremove: yes
