- name: Base system configuration
  become: true
  block:

  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{ machine_hostname }}"  # group variable

  - name: "Set timezone to {{ machine_timezone }}"
    community.general.timezone:
      name: "{{ machine_timezone }}"  # group variable
